import React, { useEffect, useState } from 'react';
import {
  View, Text, FlatList, TouchableOpacity, StyleSheet,
  SafeAreaView, ActivityIndicator, RefreshControl, Alert, Share
} from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { getRecords } from '../../services/api';
import { useAuthStore } from '../../store/authStore';

const TEAL = '#0B6E6E';

const STATUS_BG   = { pending: '#FEF3C7', accepted: '#D1FAE5', completed: '#EDE9FE' };
const STATUS_TEXT = { pending: '#92400E', accepted: '#065F46', completed: '#5B21B6' };

function fmt(ts) {
  if (!ts) return '—';
  const d = ts.toDate ? ts.toDate() : new Date(ts);
  return d.toLocaleDateString('en-ET', { year: 'numeric', month: 'short', day: 'numeric' });
}

/**
 * Generates a plain-text referral letter and shares/downloads it.
 * On Android this opens the share sheet which includes Save to Files.
 * A real PDF library (expo-print) can replace this for production.
 */
async function downloadReferral(item, patientName) {
  const lines = [
    '═══════════════════════════════════════════',
    '           MEDLINK ETHIOPIA',
    '         REFERRAL LETTER',
    '═══════════════════════════════════════════',
    '',
    `Date:            ${fmt(item.createdAt)}`,
    `Referral ID:     ${item.id || '—'}`,
    '',
    '── PATIENT ────────────────────────────────',
    `Name:            ${patientName}`,
    `Patient ID:      ${item.patientID}`,
    '',
    '── REFERRING PROVIDER ─────────────────────',
    `Doctor:          Dr. ${item.providerName}`,
    `Facility:        ${item.facilityName}`,
    '',
    '── REFERRAL DETAILS ────────────────────────',
    `Referred To:     ${item.referredTo || '—'}`,
    `Speciality:      ${item.speciality || '—'}`,
    `Urgency:         ${item.urgency    || '—'}`,
    `Reason:          ${item.reason     || '—'}`,
    '',
    '── CLINICAL SUMMARY ────────────────────────',
    item.referralSummary || 'See attached clinical notes.',
    '',
    '── CURRENT MEDICATIONS ─────────────────────',
    item.currentMedications || '—',
    '',
    '── RELEVANT HISTORY ────────────────────────',
    item.relevantHistory || '—',
    '',
    '═══════════════════════════════════════════',
    'This referral was generated by MedLink Ethiopia.',
    'Verify authenticity using the Patient ID above.',
    '═══════════════════════════════════════════',
  ].join('\n');

  try {
    await Share.share({
      title:   `Referral Letter — ${patientName}`,
      message: lines,
    });
  } catch (e) {
    Alert.alert('Error', 'Could not share referral letter.');
  }
}

export default function ReferralsScreen() {
  const activePatientID = useAuthStore(s => s.activePatientID());
  const activeProfile   = useAuthStore(s => s.activeProfile);
  const [records, setRecords]       = useState([]);
  const [loading, setLoading]       = useState(true);
  const [refreshing, setRefreshing] = useState(false);

  const patientName = [
    activeProfile?.firstName,
    activeProfile?.fatherName || activeProfile?.lastName,
  ].filter(Boolean).join(' ');

  async function load() {
    try {
      const res = await getRecords(activePatientID, 'referrals');
      setRecords(res.data.records || []);
    } catch (e) {
      console.warn('Referrals load error:', e.message);
    } finally {
      setLoading(false);
      setRefreshing(false);
    }
  }

  useEffect(() => { load(); }, [activePatientID]);

  if (loading) return <ActivityIndicator size="large" color={TEAL} style={{ marginTop: 60 }} />;

  return (
    <SafeAreaView style={{ flex: 1, backgroundColor: '#F9FAFB' }}>
      <FlatList
        data={records}
        keyExtractor={item => item.id}
        refreshControl={<RefreshControl refreshing={refreshing} onRefresh={() => { setRefreshing(true); load(); }} />}
        contentContainerStyle={{ padding: 16, paddingBottom: 40 }}
        ListEmptyComponent={
          <View style={s.empty}>
            <Ionicons name="arrow-forward-circle-outline" size={52} color="#D1D5DB" />
            <Text style={s.emptyText}>No referrals on record</Text>
          </View>
        }
        renderItem={({ item }) => (
          <View style={s.card}>
            {/* Header row */}
            <View style={s.cardHeader}>
              <View style={{ flex: 1 }}>
                <Text style={s.referredTo}>→ {item.referredTo || 'Unspecified Facility'}</Text>
                {item.speciality && (
                  <Text style={s.speciality}>{item.speciality}</Text>
                )}
              </View>
              <View style={[s.statusBadge, { backgroundColor: STATUS_BG[item.status] || '#F3F4F6' }]}>
                <Text style={[s.statusText, { color: STATUS_TEXT[item.status] || '#374151' }]}>
                  {(item.status || 'pending').toUpperCase()}
                </Text>
              </View>
            </View>

            {/* Provider */}
            <Text style={s.provider}>
              From: Dr. {item.providerName} · {item.facilityName}
            </Text>

            {/* Details grid */}
            <View style={s.detailGrid}>
              {item.urgency && (
                <DetailChip
                  icon="alert-circle-outline"
                  label="Urgency"
                  value={item.urgency}
                  color={item.urgency === 'Emergency' ? '#EF4444' : item.urgency === 'Urgent' ? '#F59E0B' : '#6B7280'}
                />
              )}
              {item.reason && (
                <DetailChip icon="clipboard-outline" label="Reason" value={item.reason} color="#374151" />
              )}
            </View>

            {/* Summary */}
            {item.referralSummary && (
              <View style={s.summaryBox}>
                <Text style={s.summaryLabel}>Clinical Summary</Text>
                <Text style={s.summaryText}>{item.referralSummary}</Text>
              </View>
            )}

            {/* Footer */}
            <View style={s.cardFooter}>
              <Text style={s.date}>{fmt(item.createdAt)}</Text>
              <TouchableOpacity
                style={s.downloadBtn}
                onPress={() => downloadReferral(item, patientName)}>
                <Ionicons name="download-outline" size={16} color="#fff" />
                <Text style={s.downloadText}>Download Letter</Text>
              </TouchableOpacity>
            </View>
          </View>
        )}
      />
    </SafeAreaView>
  );
}

function DetailChip({ icon, label, value, color }) {
  return (
    <View style={s.chip}>
      <Ionicons name={icon} size={13} color={color} />
      <Text style={s.chipLabel}>{label}: </Text>
      <Text style={[s.chipValue, { color }]}>{value}</Text>
    </View>
  );
}

const s = StyleSheet.create({
  empty:        { alignItems: 'center', marginTop: 80 },
  emptyText:    { color: '#9CA3AF', fontSize: 15, marginTop: 12 },
  card:         { backgroundColor: '#fff', borderRadius: 14, padding: 16, marginBottom: 14, borderWidth: 1, borderColor: '#E5E7EB', elevation: 2 },
  cardHeader:   { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 6 },
  referredTo:   { fontSize: 16, fontWeight: '700', color: '#111827' },
  speciality:   { fontSize: 12, color: '#6B7280', marginTop: 2 },
  statusBadge:  { borderRadius: 6, paddingHorizontal: 8, paddingVertical: 3 },
  statusText:   { fontSize: 11, fontWeight: '700' },
  provider:     { fontSize: 13, color: '#6B7280', marginBottom: 10 },
  detailGrid:   { gap: 6, marginBottom: 10 },
  chip:         { flexDirection: 'row', alignItems: 'center', gap: 4, backgroundColor: '#F9FAFB', borderRadius: 6, paddingHorizontal: 10, paddingVertical: 6 },
  chipLabel:    { fontSize: 12, color: '#6B7280' },
  chipValue:    { fontSize: 12, fontWeight: '600' },
  summaryBox:   { backgroundColor: '#F0FDFA', borderRadius: 8, padding: 12, marginBottom: 10 },
  summaryLabel: { fontSize: 11, fontWeight: '700', color: TEAL, marginBottom: 4 },
  summaryText:  { fontSize: 13, color: '#374151', lineHeight: 19 },
  cardFooter:   { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', borderTopWidth: 1, borderTopColor: '#F3F4F6', paddingTop: 10, marginTop: 4 },
  date:         { fontSize: 12, color: '#9CA3AF' },
  downloadBtn:  { flexDirection: 'row', alignItems: 'center', gap: 6, backgroundColor: TEAL, borderRadius: 8, paddingHorizontal: 14, paddingVertical: 8 },
  downloadText: { color: '#fff', fontWeight: '700', fontSize: 13 },
});